name: OpenWRT Build 23.05.5 for jdcloud_re-sp-01b

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up the environment
      - name: Set up OpenWRT build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget

      # Step 3: Clone the OpenWRT repository (if not already in the repository)
      - name: Clone OpenWRT repository
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git

      # Step 4: Checkout the correct branch
      - name: Checkout OpenWRT branch
        run: |
          cd openwrt
          git checkout main

      # Step 4.1: Update feeds
      - name: Update feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a && ./scripts/feeds install -a
          
      # Step 5: Set up configuration
      - name: Set up configuration and expand .config
        run: |
          cp jdcloud_re-sp-01b.buildinfo openwrt/.config
      
      # Step 5.1: patch the TARGET_DEVICES list
      - name: patch the TARGET_DEVICES list
        run: |
          cat jdcloud_re-sp-01b.TARGET_DEVICES >> openwrt/target/linux/ramips/image/mt7621.mk

      # Step 5.2: patch the dts
      - name: patch the dts
        run: |
          cp mt7621_jdcloud_re-sp-01b.dts openwrt/target/linux/ramips/dts/
          
      # Step 6: Run the build process
      - name: Build OpenWRT
        run: |
          cd openwrt
          make -j$(nproc) defconfig download world

      # Step 7: Archive the targets
      - name: Archive targets
        uses: actions/upload-artifact@v3
        with:
          name: targets
          path: openwrt/bin/**/*.bin
