name: build test mtk-sd fix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up OpenWRT build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: prepare OpenWRT repository
        run: |
          git clone https://github.com/grepmorecat/openwrt.git
          cd openwrt

          git remote add test-fork git@github.com:DragonBluep/openwrt.git

          git checkout add-support-jdcloud
          git fetch test-fork
          git cherry-pick  2000279^..b61ac3a
          ./scripts/feeds update -a && ./scripts/feeds install -a
          
      - name: create .config
        run: |
          cp jdcloud_re-sp-01b.buildinfo openwrt/.config
      
      - name: Build OpenWRT
        run: |
          cd openwrt
          make -j$(nproc) defconfig download world

      - name: Archive targets
        uses: actions/upload-artifact@v4
        with:
          name: targets
          path: openwrt/bin/targets/ramips/mt7621/*.bin
