name: mmc debug jdcloud

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: Prepare OpenWRT project
        run: |
          git clone https://github.com/grepmorecat/openwrt.git
          cd openwrt
          git checkout add-support-jdcloud
          ./scripts/feeds update -a && ./scripts/feeds install -a
          
      - name: Patchworks
        run: |
          cp jdcloud_re-sp-01b.buildinfo openwrt/.config
          patch openwrt/target/linux/ramips/image/mt7621.mk < ext4_support.diff
      
      - name: Build
        run: |
          cd openwrt
          make -j$(nproc) defconfig download world

      - name: Archive targets
        uses: actions/upload-artifact@v3
        with:
          name: targets
          path: openwrt/bin/targets/ramips/mt7621/*.bin
